<?php

namespace Plugin\PrizeShow\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\PrizeShow\Entity\PrizeList;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PrizeListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrizeListRepository extends AbstractRepository
{
    /**
     * PrizeListRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, PrizeList::class);
    }

    /**
     * @param int $id
     *
     * @return null|PrizeList
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    public function newPrizeList()
    {
        $prizeList = new PrizeList();

        return $prizeList;
    }
}
